name: Test ec2-hosted runner

on:
  push:
    branches: ["main"]

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  Test-aws-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create file
        run: echo  hello >> file.txt

      - name: Copy repo in another path
        run: |
          mkdir ~/${{ env.REPO_NAME }}
          rsync -avzh --delete . ${{ REPO_NAME }}
          
