name: Test ec2-hosted runner

on:
  push:
    branches: ["main"]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  DEFAULT_PATH: ~/actions-runner/_work/aws-hosted-runner/aws-hosted-runner

jobs:
  Test-aws-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create file
        run: echo  hello >> file.txt

      - name: Create directory
        run: |
          if [ ! -d "~/${{ env.REPO_NAME }}" ]; then
            mkdir ~/${{ env.REPO_NAME }}
          else
            echo "Specified directory already exists: ~/${{ env.REPO_NAME }}"
          fi
          
      - name: Copy repo in another path
        run: |
          cd ${{ env.GITHUB_WORKSPACE}}
          rsync -azh --delete --info=stats2 . ~/${{ env.REPO_NAME }}
          
