name: Test ec2-hosted runner

on:
  push:
    branches: ["main"]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  DEFAULT_PATH: $HOME/actions-runner/_work/aws-hosted-runner/aws-hosted-runner

jobs:
  Test-aws-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Execute pwd command
        run: pwd > file.tx

     
